name: sarsa
_target_: model.sarsa.SARSA

params:
  obs_dim: ??? # to be specified later
  action_dim: ??? # to be specified later
  action_range: ??? # to be specified later
  agent_index: ??? # Different by environments
  device: ${device}
  discrete_action_space: ${discrete_action_space}
  lr: 0.01
  gamma: 0.95

  critic:
    input_dim: ???